[2024-09-08T16:14:07.239+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-08T16:14:07.377+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exchange_rates_dag.run_main_script scheduled__2024-03-01T00:00:00+00:00 [queued]>
[2024-09-08T16:14:07.468+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exchange_rates_dag.run_main_script scheduled__2024-03-01T00:00:00+00:00 [queued]>
[2024-09-08T16:14:07.475+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-08T16:14:07.930+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_main_script> on 2024-03-01 00:00:00+00:00
[2024-09-08T16:14:08.009+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=274) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-08T16:14:08.026+0000] {standard_task_runner.py:72} INFO - Started process 280 to run task
[2024-09-08T16:14:08.004+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'exchange_rates_dag', 'run_main_script', 'scheduled__2024-03-01T00:00:00+00:00', '--job-id', '120', '--raw', '--subdir', 'DAGS_FOLDER/exchange_rates_dag.py', '--cfg-path', '/tmp/tmpzc2i7x38']
[2024-09-08T16:14:08.053+0000] {standard_task_runner.py:105} INFO - Job 120: Subtask run_main_script
[2024-09-08T16:14:08.466+0000] {task_command.py:467} INFO - Running <TaskInstance: exchange_rates_dag.run_main_script scheduled__2024-03-01T00:00:00+00:00 [running]> on host bd0133ae5e03
[2024-09-08T16:14:09.302+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exchange_rates_dag' AIRFLOW_CTX_TASK_ID='run_main_script' AIRFLOW_CTX_EXECUTION_DATE='2024-03-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-01T00:00:00+00:00'
[2024-09-08T16:14:09.321+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-08T16:15:06.338+0000] {local_task_job_runner.py:127} ERROR - Received SIGTERM. Terminating subprocesses
[2024-09-08T16:15:06.610+0000] {process_utils.py:132} INFO - Sending 15 to group 280. PIDs of all processes in the group: [286, 280]
[2024-09-08T16:15:06.825+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 280
[2024-09-08T16:15:06.877+0000] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-09-08T16:15:07.926+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=286, status='terminated', started='16:14:09') (286) terminated with exit code None
[2024-09-08T16:15:08.029+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/exchange_rates_dag.py", line 27, in run_main
    subprocess.run(["python3", "/opt/airflow/main.py"], check=True)
  File "/usr/local/lib/python3.12/subprocess.py", line 550, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 1201, in communicate
    self.wait()
  File "/usr/local/lib/python3.12/subprocess.py", line 1264, in wait
    return self._wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 2053, in _wait
    (pid, sts) = self._try_wait(0)
                 ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 2011, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3094, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-09-08T16:15:08.594+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=exchange_rates_dag, task_id=run_main_script, run_id=scheduled__2024-03-01T00:00:00+00:00, execution_date=20240301T000000, start_date=20240908T161407, end_date=20240908T161508
[2024-09-08T16:15:10.453+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-08T16:15:10.667+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=280, status='terminated', exitcode=2, started='16:14:07') (280) terminated with exit code 2
[2024-09-08T16:15:10.698+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 143
[2024-09-08T16:15:10.987+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-08T16:15:11.263+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-09-15T05:54:09.407+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-15T05:54:09.578+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exchange_rates_dag.run_main_script scheduled__2024-03-01T00:00:00+00:00 [queued]>
[2024-09-15T05:54:09.664+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exchange_rates_dag.run_main_script scheduled__2024-03-01T00:00:00+00:00 [queued]>
[2024-09-15T05:54:09.671+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-15T05:54:09.916+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_main_script> on 2024-03-01 00:00:00+00:00
[2024-09-15T05:54:09.976+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=574) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-15T05:54:09.991+0000] {standard_task_runner.py:72} INFO - Started process 583 to run task
[2024-09-15T05:54:09.981+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'exchange_rates_dag', 'run_main_script', 'scheduled__2024-03-01T00:00:00+00:00', '--job-id', '176', '--raw', '--subdir', 'DAGS_FOLDER/exchange_rates_dag.py', '--cfg-path', '/tmp/tmpfjaj00nv']
[2024-09-15T05:54:10.001+0000] {standard_task_runner.py:105} INFO - Job 176: Subtask run_main_script
[2024-09-15T05:54:10.353+0000] {task_command.py:467} INFO - Running <TaskInstance: exchange_rates_dag.run_main_script scheduled__2024-03-01T00:00:00+00:00 [running]> on host ed6b7035df5d
[2024-09-15T05:54:10.991+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***docker@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exchange_rates_dag' AIRFLOW_CTX_TASK_ID='run_main_script' AIRFLOW_CTX_EXECUTION_DATE='2024-03-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-01T00:00:00+00:00'
[2024-09-15T05:54:11.007+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-15T05:55:01.511+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-15T05:55:01.528+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-15T05:55:01.530+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=exchange_rates_dag, task_id=run_main_script, run_id=scheduled__2024-03-01T00:00:00+00:00, execution_date=20240301T000000, start_date=20240915T055409, end_date=20240915T055501
[2024-09-15T05:55:01.574+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-15T05:55:01.606+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-15T05:55:01.615+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
