[2024-09-08T16:14:06.519+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-08T16:14:06.615+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exchange_rates_dag.run_main_script scheduled__2024-02-29T00:00:00+00:00 [queued]>
[2024-09-08T16:14:06.670+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exchange_rates_dag.run_main_script scheduled__2024-02-29T00:00:00+00:00 [queued]>
[2024-09-08T16:14:06.675+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-08T16:14:06.832+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_main_script> on 2024-02-29 00:00:00+00:00
[2024-09-08T16:14:06.881+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=269) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-08T16:14:06.898+0000] {standard_task_runner.py:72} INFO - Started process 276 to run task
[2024-09-08T16:14:06.884+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'exchange_rates_dag', 'run_main_script', 'scheduled__2024-02-29T00:00:00+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/exchange_rates_dag.py', '--cfg-path', '/tmp/tmpbjzdfve0']
[2024-09-08T16:14:06.908+0000] {standard_task_runner.py:105} INFO - Job 119: Subtask run_main_script
[2024-09-08T16:14:07.254+0000] {task_command.py:467} INFO - Running <TaskInstance: exchange_rates_dag.run_main_script scheduled__2024-02-29T00:00:00+00:00 [running]> on host bd0133ae5e03
[2024-09-08T16:14:07.975+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exchange_rates_dag' AIRFLOW_CTX_TASK_ID='run_main_script' AIRFLOW_CTX_EXECUTION_DATE='2024-02-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-29T00:00:00+00:00'
[2024-09-08T16:14:07.982+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-08T16:15:06.350+0000] {local_task_job_runner.py:127} ERROR - Received SIGTERM. Terminating subprocesses
[2024-09-08T16:15:06.586+0000] {process_utils.py:132} INFO - Sending 15 to group 276. PIDs of all processes in the group: [283, 276]
[2024-09-08T16:15:06.720+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 276
[2024-09-08T16:15:06.797+0000] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-09-08T16:15:07.406+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=283, status='terminated', started='16:14:07') (283) terminated with exit code None
[2024-09-08T16:15:07.886+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/exchange_rates_dag.py", line 27, in run_main
    subprocess.run(["python3", "/opt/airflow/main.py"], check=True)
  File "/usr/local/lib/python3.12/subprocess.py", line 550, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 1201, in communicate
    self.wait()
  File "/usr/local/lib/python3.12/subprocess.py", line 1264, in wait
    return self._wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 2053, in _wait
    (pid, sts) = self._try_wait(0)
                 ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 2011, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3094, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-09-08T16:15:08.573+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=exchange_rates_dag, task_id=run_main_script, run_id=scheduled__2024-02-29T00:00:00+00:00, execution_date=20240229T000000, start_date=20240908T161406, end_date=20240908T161508
[2024-09-08T16:15:10.483+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-08T16:15:10.630+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=276, status='terminated', exitcode=2, started='16:14:06') (276) terminated with exit code 2
[2024-09-08T16:15:10.647+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 143
[2024-09-08T16:15:10.980+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-08T16:15:11.273+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-09-15T05:54:08.592+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-15T05:54:08.705+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exchange_rates_dag.run_main_script scheduled__2024-02-29T00:00:00+00:00 [queued]>
[2024-09-15T05:54:08.789+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exchange_rates_dag.run_main_script scheduled__2024-02-29T00:00:00+00:00 [queued]>
[2024-09-15T05:54:08.795+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-15T05:54:08.975+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_main_script> on 2024-02-29 00:00:00+00:00
[2024-09-15T05:54:09.027+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=573) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-15T05:54:09.045+0000] {standard_task_runner.py:72} INFO - Started process 579 to run task
[2024-09-15T05:54:09.026+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'exchange_rates_dag', 'run_main_script', 'scheduled__2024-02-29T00:00:00+00:00', '--job-id', '175', '--raw', '--subdir', 'DAGS_FOLDER/exchange_rates_dag.py', '--cfg-path', '/tmp/tmpflyya_da']
[2024-09-15T05:54:09.062+0000] {standard_task_runner.py:105} INFO - Job 175: Subtask run_main_script
[2024-09-15T05:54:09.396+0000] {task_command.py:467} INFO - Running <TaskInstance: exchange_rates_dag.run_main_script scheduled__2024-02-29T00:00:00+00:00 [running]> on host ed6b7035df5d
[2024-09-15T05:54:10.060+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***docker@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exchange_rates_dag' AIRFLOW_CTX_TASK_ID='run_main_script' AIRFLOW_CTX_EXECUTION_DATE='2024-02-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-29T00:00:00+00:00'
[2024-09-15T05:54:10.078+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-15T05:54:54.912+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-15T05:54:55.016+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-15T05:54:55.024+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=exchange_rates_dag, task_id=run_main_script, run_id=scheduled__2024-02-29T00:00:00+00:00, execution_date=20240229T000000, start_date=20240915T055408, end_date=20240915T055455
[2024-09-15T05:54:55.169+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-15T05:54:55.457+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-15T05:54:55.510+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
